title: Iroda Radjabova
logo: https://github.com/IrodaRadjabova/irodaradjabova.github.io/blob/main/astrum.jpg
description: Healthcare Data Scientist
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
